#!/usr/bin/env bash

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create an index.html page with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Perform a 301 Redirection
string_for_replacement="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart
