#!/usr/bin/env bash

# Updating Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Performing a 301 Redirection
sudo cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location /redirect_me {
        return 301 https://www.example.com/new-page;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restarting Nginx service
if sudo service nginx status >/dev/null 2>&1; then
    sudo service nginx restart
else
    sudo service nginx start
fi
