#!/usr/bin/env bash
# Customizing a 404-error_page

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configuring the 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Adding configuration for 404 error handling to Nginx default site configuration
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 https://github.com/besthor;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
" | sudo tee /etc/nginx/sites-available/default

# Testing configurations for syntax errors
sudo nginx -t

# Restarting Nginx to apply changes
sudo service nginx restart
